### ISSUE TITLE
http://opensourceforshopify.com/ is down

### ISSUE THREAD

**Issue by JoshHighland** [discolabs/opensourceforshopify.com#3]
http://opensourceforshopify.com/ does not resolve

**Comment by gavinballard** [comment]
@JoshHighland I let the domain expire as I didn't have the time to maintain it, there wasn't much traffic to the site, and I'd received some feedback from Shopify that they felt the name / appearance of the site was confusingly close to the "official" page.

Totally happy for someone else to take the fork and domain name and continue with it though if desired!
