### ISSUE TITLE
http://opensourceforshopify.com Is down

### ISSUE THREAD

**Issue by alexandresaiz** [discolabs/opensourceforshopify.com#4]
http://opensourceforshopify.com Is down

**Comment by gavinballard** [comment]
@alexandresaiz We're stopped maintaining the site, as (a) it wasn't getting much traffic or anything in the way of new submissions; and (b) we'd had some complaints from Shopify regarding the domain name and the fact that the design was potentially confusing for users. When the domain name came up for renewal we decided it wasn't worth it.

Anyone wanting to is welcome to fork, rebrand and relaunch the idea and I will happily direct people there from this repository.
